#Updated configuration
#Tue Apr 07 21:23:13 CST 2026
AI_MODEL=qwen3.6-plus
DEFAULT_LISTVIEW_TAB=2
RESULT_FETCH_PER_TIME=200
SPLIT_DRIVER_MAIN=0.4765625
SPLIT_DRIVER_SQL=0.6
SQL_EDITOR_FONT_SIZE=9
UI_LANG=zh-CN
