#Updated configuration
<<<<<<< HEAD
#Wed Apr 01 17:48:43 CST 2026
=======
#Wed Apr 01 17:18:33 CST 2026
>>>>>>> a9975377c88885cb73d4269f1932d5974cf5d5d2
DEFAULT_LISTVIEW_TAB=0
RESULT_FETCH_PER_TIME=200
SPLIT_DRIVER_MAIN=0.2390625
SPLIT_DRIVER_SQL=0.6
SQL_EDITOR_FONT_SIZE=12
UI_LANG=zh-CN
